Cine/Cine/Controllers/GendersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cine.DAL;
using Cine.DAL.Entities;

namespace Cine.Controllers
{
    public class GendersController : Controller
    {
        private readonly DataBaseContext _context;

        public GendersController(DataBaseContext context)
        {
            _context = context;
        }

        // GET: Genders
        public async Task<IActionResult> Index()
        {
              return View(await _context.Genders.ToListAsync());
        }

        // GET: Genders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Genders == null)
            {
                return NotFound();
            }

            var gender = await _context.Genders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gender == null)
            {
                return NotFound();
            }

            return View(gender);
        }

        // GET: Genders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Gender gender)
        {
            if (ModelState.IsValid)
            {

                // Verificar si ya existe un Genero con el mismo nombre
                bool Exists = await _context.Genders
                    .AnyAsync(v => v.GenderName == gender.GenderName);

                if (Exists) // Se valida si el resultado de la variable es true o false
                {
                    // Si la variable es true se envia un mensaje 
                    ModelState.AddModelError(string.Empty, "Ya se ha registrado el genero con el mismo nombre");
                    TempData["GeneroIngresada"] = "No Se ingreso correctamente";
                }
                else
                { // Si la variable es false entonces se crea la clasificación
                    try
                    {
                        TempData["GeneroIngresada"] = "Se ingreso correctamente";
                        gender.CreatedDate = DateTime.Now;
                        _context.Add(gender);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    catch (Exception exception)
                    {
                        ModelState.AddModelError(string.Empty, exception.Message);
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(gender);

           
        }

        // GET: Genders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Genders == null)
            {
                return NotFound();
            }

            var gender = await _context.Genders.FindAsync(id);
            if (gender == null)
            {
                return NotFound();
            }
            return View(gender);
        }

        // POST: Genders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Gender gender)
        {
            if (id != gender.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    TempData["GeneroEditada"] = "Se modifico correctamente";
                    gender.ModifiedDate = DateTime.UtcNow;
                    _context.Update(gender);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenderExists(gender.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(gender);
        }

        // GET: Genders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Genders == null)
            {
                return NotFound();
            }

            var gender = await _context.Genders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gender == null)
            {
                return NotFound();
            }

            return View(gender);
        }

        // POST: Genders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Genders == null)
            {
                return Problem("Entity set 'DataBaseContext.Genders'  is null.");
            }
            var gender = await _context.Genders.FindAsync(id);
            if (gender != null)
            {
                _context.Genders.Remove(gender);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenderExists(int id)
        {
          return _context.Genders.Any(e => e.Id == id);
        }
    }
}

Cine/Cine/Controllers/HoursController.cs
using Cine.DAL;
using Cine.DAL.Entities;
using Cine.Helpers;
using Cine.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Cine.Controllers
{
    public class HoursController : Controller
    {
        private readonly DataBaseContext _context;
        private readonly IDropDownListHelper _dropDownListHelper;

        public HoursController(DataBaseContext context, IDropDownListHelper dropDownListHelper)
        {
            _context= context;
            _dropDownListHelper = dropDownListHelper;
        }
        // GET: Genders
        public async Task<IActionResult> Index()
        {
            return View(await _context.Hours.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {

            AddHourViewModel addHourViewModel = new()
            {
                Movies = await _dropDownListHelper.GetDDLMoviesAsync(),
                
            };

            return View(addHourViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddHourViewModel addHourViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {


                    Hour hour = new()
                    {
                        StarTime = addHourViewModel.StarTime,
                       
                        Date = addHourViewModel.Date,                      
                        CreatedDate = DateTime.Now,
                        Movie = await _context.Movies.FindAsync(addHourViewModel.MovieId),
    
                    };





                    _context.Add(hour);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        ModelState.AddModelError(string.Empty, "Ya existe un producto con el mismo nombre.");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                    }
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }


            addHourViewModel.Movies = await _dropDownListHelper.GetDDLMoviesAsync();
            
            return View(addHourViewModel);
        }
    }
}

Cine/Cine/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cine.DAL;
using Cine.DAL.Entities;
using Cine.Models;

namespace Cine.Controllers
{
    public class RoomsController : Controller
    {
        private readonly DataBaseContext _context;

        public RoomsController(DataBaseContext context)
        {
            _context = context;
        }

        // GET: Rooms
        public async Task<IActionResult> Index()
        {
              return View(await _context.Rooms
                  .Include(s => s.Seats)
                  .ToListAsync());
        }

        // GET: Rooms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Rooms == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .Include(s => s.Seats)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Rooms/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Room room)
        {
            if (ModelState.IsValid)
            {

                // Verificar si ya existe un el Número de la sala
                bool Exists = await _context.Rooms
                    .AnyAsync(v => v.NumberRoom == room.NumberRoom );

                if (Exists) // Se valida si el resultado de la variable es true o false
                {
                    // Si la variable es true se envia un mensaje 
                    ModelState.AddModelError(string.Empty, "El número de sala ya existe");
                    TempData["SalaIngresada"] = "No Se ingreso correctamente";
                }
                else
                { // Si la variable es false entonces se crea la clasificación
                    try
                    {
                        TempData["SalaIngresada"] = "Se ingreso correctamente";
                       
                        room.CreatedDate = DateTime.Now;
                        _context.Add(room);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    catch (Exception exception)
                    {
                        ModelState.AddModelError(string.Empty, exception.Message);
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(room);

        }

        // GET: Rooms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Rooms == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,Room room)
        {
            if (id != room.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    room.ModifiedDate = DateTime.Now;
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Rooms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Rooms == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Rooms == null)
            {
                return Problem("Entity set 'DataBaseContext.Rooms'  is null.");
            }
            var room = await _context.Rooms.FindAsync(id);
            if (room != null)
            {
                _context.Rooms.Remove(room);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(int id)
        {
          return _context.Rooms.Any(e => e.Id == id);
        }

















        [HttpGet]
        public async Task<IActionResult> AddSeat(int? roomId)
        {

            if (roomId == null) return NotFound();

            Room room = await _context.Rooms.FirstOrDefaultAsync(c => c.Id == roomId);

            if (room == null) return NotFound();

            SeatViewModel seatViewModel = new()
            {
                RoomId = room.Id,
            };

            return View(seatViewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddSeat(SeatViewModel seatViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Seat seat = new()
                    {

                        Room = await _context.Rooms.FirstOrDefaultAsync(c => c.Id == seatViewModel.RoomId),
                        NumberSeat = seatViewModel.NumberSeat,
                        Busy = false,
                        CreatedDate = DateTime.Now,
                        ModifiedDate = null,
                    };

                    _context.Add(seat);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index), new { Id = seatViewModel.RoomId });
                    //return RedirectToAction(nameof(Details), new { Id = seatViewModel.RoomId });
                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                        ModelState.AddModelError(string.Empty, "Ya existe una silla con el mismo nombre en esta sala.");
                    else
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }
            return View(seatViewModel);
        }
    }
}

Cine/Cine/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cine</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Cine.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cine</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                            </li>

                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="text-dark dropdown-item" asp-area="" asp-controller="Classifications" asp-action="Index">Clasificación de Peliculas</a>
                            </li>
                            <li class="nav-item">
                                <a class="text-dark dropdown-item" asp-area="" asp-controller="Genders" asp-action="Index">Generos de Peliculas</a>
                            </li>
                            <li class="nav-item">
                                <a class="text-dark dropdown-item" asp-area="" asp-controller="Rooms" asp-action="Index">Salas del Cine</a>
                            </li>
                            <li class="nav-item">
                                <a class="text-dark dropdown-item" asp-area="" asp-controller="Movies" asp-action="Index">Peliculas</a>
                            </li>
                            <li class="nav-item">
                                <a class="text-dark dropdown-item" asp-area="" asp-controller="Hours" asp-action="Index">Horarios</a>
                            </li>

                        }
                        @if (User.Identity.IsAuthenticated && User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                            </li>

                        }


                        </ul>
                    
                    <ul class="nav navbar-nav navbar-right">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="EditUser">@User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Cerrar Sesión</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Iniciar Sesión</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Cine - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>